apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - image: ssilvestro/api-gateway
          name: gateway
          ports:
            - containerPort: 9191
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
    - name: "9191"
      port: 9191
      targetPort: 9191
  selector:
    io.kompose.service: gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api-service
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-service
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: api-service
    spec:
      containers:
        - image: ssilvestro/api-service
          name: api-service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api-service
  name: api-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: api-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: position-service
  name: position-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: position-service
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: position-service
    spec:
      containers:
        - image: ssilvestro/position-service
          name: position-service
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: position-service
  name: position-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: position-service
